<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <nullable>enable</nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq" Version="4.17.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\U2U.Games.Core\U2U.Games.Core.csproj" />
    <ProjectReference Include="..\..\src\U2U.Games.Infra\U2U.Games.Infra.csproj" />
  </ItemGroup>

</Project>
